### ISSUE TITLE
SECRET_KEY?

### ISSUE THREAD

**Issue by jonschlinkert** [doowb/search-indexer-algolia#1]
Is that supposed to be "search key"? Or "api key"?

**Comment by redox** [comment]
> Is that supposed to be "search key"? Or "api key"?

It must be a write-capable API key, for instance the ADMIN API key.

You cannot use the "Search API key" as it's only able to do search queries and not indexing.

**Comment by doowb** [comment]
Yeah, @redox is correct. I should update it to align with what algolia calls the key and specify that in the docs. 

I used "secret" because other services use words like "client secret" to indicate that it's something that shouldn't be shared publicly.

**Comment by jonschlinkert** [comment]
> You cannot use the "Search API key" as it's only able to do search queries and not indexing.

I was about to come back on and state almost the same thing. We're learning algolia's API atm. Thanks for the confirmation!

**Comment by doowb** [comment]
The option has been updated to `API_KEY` to match algolia's api. `SECRET_KEY` will still work for now.
